### ISSUE TITLE
How do I load a custom model

### ISSUE THREAD

**Issue by suyashjoshi** [readyplayerme/Example-iOS-Swift#8]
I wanted to try your iOS SDK to load the model file - avatar that I created using your web app on iOS and then use it for an AR App however the sample code doesn't seem to be working when I change the URL to the 'glb' file URL. How do I load custom model using this sample project? 

Inside **WebViewController.swift :  What does the URL do and can this be custom model file ?**
```
func reloadPage(clearHistory : Bool){
        let url = URL(string: "url-was-here")!
        if(clearHistory){
            WebCacheCleaner.clean()
        }
        webView.load(URLRequest(url: url))
    }
```

**Comment by HarrisonHough** [comment]
The URL here is telling the WebView which webpage to load, like you would tell an iframe which page to load. So passing a .glb url here won't work. 
The purpose of this webview is to enable avatar creation within an iOS app by displaying our web avatar creator and returning the avartar .glb url. 
We don't currently provide an example of how to display or render this model using native API's. We leave this for developers to implement however best suits their application.
